#Uncomment the next line to define a global platform for your project
platform :ios, '17.5'

target 'M-Cals' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GRDB.swift'
  pod 'FirebaseAnalytics'
  # Pods for Mkcals

end
